### ISSUE TITLE
Firefox "Unhandled JavaScript exception:  "

### ISSUE THREAD

**Issue by fgutmann** [JetBrains/kotlin-playground#43]
When executing the following code on Firefox  64.0.2  on Mac OS, the result is `Unhandeled Javascript Exception`. It works fine in Chrome.

```
import org.w3c.dom.CanvasRenderingContext2D
import org.w3c.dom.HTMLCanvasElement
import kotlin.browser.document

fun main() {
    val canvas = document.createElement("canvas") as HTMLCanvasElement
    
    val context2d = canvas.getContext("2d") as CanvasRenderingContext2D
    context2d.font = "14px Arial" // crashes exactly here

    document.body!!.append(canvas)
}
```

It took quite some time to isolate the issue because there is no error description at all. The error handling code in `showJsException(e)` fails to extract the information of this exception. Logging the exception to the console gives some useful information. Therefore I propose to log the raw exceptions to the console in addition to displaying them nicely.

The above code works also fine in Firefox when:
- It is run outside the kotlin-playground
- Or when the canvas is appended to the body before accessing the rendering context

I think the underlying issue has to do with how the iframe is created and initialized. Could be related to #28.

**Comment by AlexanderPrendota** [comment]
Hey! Should we close that issue? =) #28 was fixed.

**Comment by fgutmann** [comment]
Hi :-)

Unfortunately the issue still exists. But by now I don't think the root cause of it is to be found in the kotlin-playground library.

All that can be done from this side is to provide better error logging. I created https://github.com/JetBrains/kotlin-playground/pull/52 for this.

For people with the same issue: When the canvas is added to the DOM before accessing the context, everything works well.
